### ISSUE TITLE
[Question❓]: Can't open the app after modifying Theme JSON

### ISSUE THREAD

**Issue by GetcharWu** [davidsmorais/kuro#102]
# Can't open the app after modifying Theme JSON❓

First of all, I'm not quite sure it's a bug, so I'm categorized as Question.

**Describe the bug**
I opened the app after modifying the theme json based on [orychalk's Light theme ](https://github.com/davidsmorais/kuro/wiki/Custom-Themes-%F0%9F%8E%A8#orychalks-light)in the wiki and encountered an error.

**Reproduction Steps**
Directly modify the theme JSON to @orychalk's Light JSON.(I was able to make sure I modified it correctly, because I copied and pasted it directly.) Reopen the app.

**Expected Behavior**
I hope that even if the wrong theme JSON is modified, the app will start correctly.

**Technical Info (please complete the following information)**
 - OS: Ubuntu 20.04
 - Kuro Version: 9.0.0

**Additional context**
I have tried to reinstall kuro and to delete the configuration files under ~/.config, both did nothing to help the problem.When I launch from the terminal, it prompts the following error:
``` shell
❯ ./kuro
SyntaxError: Unexpected non-whitespace character after JSON at position 1771
    at JSON.parse (<anonymous>)
    at get _local [as _local] (/opt/Kuro/resources/app.asar/src/config.js:15:19)
    at Config._ensureLocalConfig (/opt/Kuro/resources/app.asar/src/config.js:58:33)
    at get configuration [as configuration] (/opt/Kuro/resources/app.asar/src/config.js:22:10)
    at get shortcutKeys [as shortcutKeys] (/opt/Kuro/resources/app.asar/src/config.js:27:17)
    at Object.<anonymous> (/opt/Kuro/resources/app.asar/src/keymap.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Config._updateConfig (/opt/Kuro/resources/app.asar/src/config.js:37:12)
    at Config._ensureLocalConfig (/opt/Kuro/resources/app.asar/src/config.js:58:14)
    at get configuration [as configuration] (/opt/Kuro/resources/app.asar/src/config.js:22:10)
    at get shortcutKeys [as shortcutKeys] (/opt/Kuro/resources/app.asar/src/config.js:27:17)
    at Object.<anonymous> (/opt/Kuro/resources/app.asar/src/keymap.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
```
---
cc:
@davidsmorais

**Comment by orychalk** [comment]
Hello,

Could you show me your /home/"USER"/.kuro.json ?

**Comment by GetcharWu** [comment]
Thanks for replying so quickly.
Based on your tips, I have found this config file and found the problem with it: Thank you.

**Comment by davidsmorais** [comment]
It's usually something like that, or a rogue comma :) 

Closing the issuee
