### ISSUE TITLE
Crashes on launch [Bug 🐞]: 

### ISSUE THREAD

**Issue by stephanlamoureux** [davidsmorais/kuro#103]
# Won't Launch🐞

**Describe the bug**
Kuro crashes on launch.

<details>
<summary>journalctl log</summary>
<pre>
Jun 30 18:36:11 fedora systemd[2023]: Started snap.kuro-desktop.kuro-desktop.1e971b78-487d-47db-a5f7-2544c11203a6.scope.
Jun 30 18:36:11 fedora audit: BPF prog-id=161 op=LOAD
Jun 30 18:36:11 fedora systemd[2023]: Started app-kuro\x2ddesktop_kuro\x2ddesktop-1c0ae609e7654ac695ae9776035bca82.scope - Kuro.
Jun 30 18:36:11 fedora audit: BPF prog-id=161 op=UNLOAD
Jun 30 18:36:11 fedora audit[32691]: SECCOMP auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=32691 comm="kuro-desktop" exe="/snap/kuro-desktop/72/kuro-desktop" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7f437a5834e7 code=0x50000
Jun 30 18:36:12 fedora plasmashell[32691]: A JavaScript error occurred in the main process
Jun 30 18:36:12 fedora plasmashell[32691]: Uncaught Exception:
Jun 30 18:36:12 fedora plasmashell[32691]: SyntaxError: Unexpected end of JSON input
Jun 30 18:36:12 fedora plasmashell[32691]:     at JSON.parse (<anonymous>)
Jun 30 18:36:12 fedora plasmashell[32691]:     at Conf._deserialize (/snap/kuro-desktop/72/resources/app.asar/node_modules/conf/dist/source/index.js:67:43)
Jun 30 18:36:12 fedora plasmashell[32691]:     at get store [as store] (/snap/kuro-desktop/72/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
Jun 30 18:36:12 fedora plasmashell[32691]:     at new Conf (/snap/kuro-desktop/72/resources/app.asar/node_modules/conf/dist/source/index.js:131:32)
Jun 30 18:36:12 fedora plasmashell[32691]:     at new ElectronStore (/snap/kuro-desktop/72/resources/app.asar/node_modules/electron-store/index.js:69:3)
Jun 30 18:36:12 fedora plasmashell[32691]:     at Object.<anonymous> (/snap/kuro-desktop/72/resources/app.asar/src/settings.js:6:15)
Jun 30 18:36:12 fedora plasmashell[32691]:     at Module._compile (node:internal/modules/cjs/loader:1141:14)
Jun 30 18:36:12 fedora plasmashell[32691]:     at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
Jun 30 18:36:12 fedora plasmashell[32691]:     at Module.load (node:internal/modules/cjs/loader:1011:32)
Jun 30 18:36:12 fedora plasmashell[32691]:     at Module._load (node:internal/modules/cjs/loader:846:12)
Jun 30 18:36:12 fedora kuro-desktop[32691]: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
Jun 30 18:36:12 fedora kuro-desktop[32691]: Failed to load module "colorreload-gtk-module"
Jun 30 18:36:12 fedora kuro-desktop[32691]: Failed to load module "window-decorations-gtk-module"
Jun 30 18:36:29 fedora systemd[1]: fprintd.service: Deactivated successfully.
Jun 30 18:36:29 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=fprintd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 30 18:36:29 fedora audit: BPF prog-id=160 op=UNLOAD
Jun 30 18:39:49 fedora PackageKit[28701]: daemon quit
Jun 30 18:39:49 fedora plasma-discover[28689]: PackageKit stopped running!
Jun 30 18:39:49 fedora systemd[1]: packagekit.service: Deactivated successfully.
Jun 30 18:39:49 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=packagekit comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jun 30 18:39:49 fedora systemd[1]: packagekit.service: Consumed 5.066s CPU time.
</pre>
</details>

**Technical Info (please complete the following information)**
 - OS: Fedora 38 w/ KDE Plasma 5.27.6
 - Kuro Version: Latest

**Additional context**
Tried reinstalling.

---
cc:
@davidsmorais

**Comment by stephanlamoureux** [comment]
switched from snap to rpm 👍
