### ISSUE TITLE
AUR package for Arch Linux

### ISSUE THREAD

**Issue by kellerman** [davidsmorais/kuro#22]
Hello. I seem to find the .pacman file which could be installed locally by using pacman -U. But cant seem to find a AUR package. Installing and from AUR would be very much easier.
I think modifying the ao pkgbuild slightly would do the job.

**Comment by davidsmorais** [comment]
Hey :wave:  I'm not a very experienced Arch user, I thought the `pacman` package would suffice as in my experience with Arch was easier to install `pacman` than `AUR`.
I've picked up [some](https://wiki.archlinux.org/title/Electron_package_guidelines) [articles](https://wiki.archlinux.org/title/Electron_package_guidelines) and this seems feasible, so I'll work on adding an AUR package when I have the time, but if someone wants to have a go at it, feel free :+1:

**Comment by MaaxGr** [comment]
isn't this your AUR package? https://aur.archlinux.org/packages/ao

**Comment by davidsmorais** [comment]
No, it is not :disappointed:

**Comment by MaaxGr** [comment]
So someone else is just using your upstream? :D

**Comment by davidsmorais** [comment]
@MaaxGr  Indeed :point_down: 
![image](https://user-images.githubusercontent.com/22729436/167376817-56f34ac6-ad3b-4b8b-999b-03426b484253.png)

I need to get around to publish Kuro in AUR, but I don't use Arch Linux and I've had a little difficulty  trying to set up the publishing environment. Hopefully in the next weeks I'll take care of this

**Comment by Reverier-Xu** [comment]
```
# Maintainer: ???
pkgname=kuro-appimage
pkgver=8.1.3
pkgrel=1
pkgdesc="An elegant Microsoft ToDo desktop client for Linux (a fork of Ao)"
arch=("x86_64")
url="https://github.com/davidsmorais/kuro"
license=("unknown")
_pkgname="Kuro-${pkgver}.AppImage"
noextract=(${_pkgname})
options=("!strip")
provides=("kuro")
optdepends=()
source=("https://github.com/davidsmorais/kuro/releases/download/v${pkgver}/${_pkgname}")
sha512sums=("SKIP")

_installdir=/opt/kuro

prepare() {
    cd ${srcdir}
    chmod a+x ${_pkgname}
    ${srcdir}/${_pkgname} --appimage-extract >/dev/null
    sed -i "s+AppRun+env DESKTOPINTEGRATION=no ${_installdir}/Kuro.AppImage+" "squashfs-root/kuro.desktop"
    sed -i "s+Icon=kuro+Icon=kuro-appimage+" "squashfs-root/kuro.desktop"
}

package() {
    install -Dm755 ${_pkgname} "${pkgdir}/${_installdir}/Kuro.AppImage"
    install -Dm644 "squashfs-root/usr/share/icons/hicolor/1024x1024/apps/kuro.png" "${pkgdir}/usr/share/icons/hicolor/1024x1024/apps/kuro-appimage.png"
    install -Dm644 "squashfs-root/usr/share/icons/hicolor/512x512/apps/kuro.png" "${pkgdir}/usr/share/icons/hicolor/512x512/apps/kuro-appimage.png"
    install -Dm644 "squashfs-root/usr/share/icons/hicolor/256x256/apps/kuro.png" "${pkgdir}/usr/share/icons/hicolor/256x256/apps/kuro-appimage.png"
    install -Dm644 "squashfs-root/usr/share/icons/hicolor/128x128/apps/kuro.png" "${pkgdir}/usr/share/icons/hicolor/128x128/apps/kuro-appimage.png"
    install -Dm644 "squashfs-root/kuro.desktop" "${pkgdir}/usr/share/applications/kuro-appimage.desktop"
}
```

this PKGBUILD file may helps.

but version 8.1.3 doesn't work, you can change `pkgver` to `8.1.0`( #37 ) and change `_pkgname` from `Kuro-${pkgver}.AppImage` to `Kuro.${pkgver}.AppImage`. then, just run `makepkg -sri` and it works.

@davidsmorais if you can name the package with a fixed naming scheme, then after you release an update , you just need to change the version number here then update the sha512 value and push it to the AUR.

i'd like to become the AUR package maintainer but i have my own works to do... so i'm sorry for that.

**Comment by Reverier-Xu** [comment]
Published `kuro-appimage` in AUR.

https://aur.archlinux.org/packages/kuro-appimage

```
paru -S kuro-appimage
```

or 

```
yay -S kuro-appimage
```

**Comment by davidsmorais** [comment]
Hey @bilal-tasdelen 👋 

When I forked Ao, my intention was to get it working to as many Linux users as possible, so I thank you for changing Ao's upstream to Kuro👌  I also have no problem at all with you keeping ownership of the current Ao AUR package or even open a new one for Kuro. 
But it's like I said before, I don't have much experience with Arch, so I'm cool if someone else wants to help deploy this to AUR in any format, while I don't get around to it 😓

**Comment by davidsmorais** [comment]
Thank you :heart:

**Comment by shmu26** [comment]
Thanks for publishing packages on AUR. You even have an App-image over there, which is great, because it installs on my Manjaro system without hitch. 
Could you maybe update the App-image on AUR to the newest version?

**Comment by shmu26** [comment]
With the regular AUR package, I got the following error:
`Preparing…
Synchronizing package databases…
unable to lock database
Failed to synchronize databases
Refreshing AUR…
Cloning kuro build files…
Generating kuro information…
Checking kuro dependencies…
Resolving dependencies…
Checking inter-conflicts…

Building kuro…
==> Making package: kuro 8.1.6-3 (Fri 16 Dec 2022 03:06:26 PM IST)
==> Checking runtime dependencies…
==> Checking buildtime dependencies…
==> Retrieving sources…
-> Found kuro
-> Found kuro.desktop
-> Downloading kuro-8.1.6.tar.gz…
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed

0 0 0 0 0 0 0 0 --:–:-- --:–:-- --:–:-- 0
0 0 0 0 0 0 0 0 --:–:-- --:–:-- --:–:-- 0
0 0 0 0 0 0 0 0 --:–:-- --:–:-- --:–:-- 0

0 0 0 0 0 0 0 0 --:–:-- 0:00:01 --:–:-- 0
0 0 0 0 0 0 0 0 --:–:-- 0:00:02 --:–:-- 0
0 0 0 0 0 0 0 0 --:–:-- 0:00:03 --:–:-- 0
0 0 0 0 0 0 0 0 --:–:-- 0:00:04 --:–:-- 0
0 0 0 0 0 0 0 0 --:–:-- 0:00:05 --:–:-- 0
100 730 0 730 0 0 116 0 --:–:-- 0:00:06 --:–:-- 142
100 551k 0 551k 0 0 78985 0 --:–:-- 0:00:07 --:–:-- 111k
100 720k 0 720k 0 0 97k 0 --:–:-- 0:00:07 --:–:-- 173k
==> Validating source files with sha256sums…
kuro … Passed
kuro.desktop … Passed
kuro-8.1.6.tar.gz … Passed
==> Removing existing $srcdir/ directory…
==> Extracting sources…
-> Extracting kuro-8.1.6.tar.gz with bsdtar
==> Starting build()…
yarn install v1.22.19
[1/4] Resolving packages…
[2/4] Fetching packages…
[3/4] Linking dependencies…
warning “xo > eslint-import-resolver-webpack@0.13.2” has unmet peer dependency “webpack@>=1.11.0”.
[4/4] Building fresh packages…
error /var/tmp/pamac-build-shmuel/kuro/src/kuro-8.1.6/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /var/tmp/pamac-build-shmuel/kuro/src/kuro-8.1.6/node_modules/electron
Output:
RequestError: unable to verify the first certificate
at ClientRequest.<anonymous> (/var/tmp/pamac-build-shmuel/kuro/src/kuro-8.1.6/node_modules/got/source/request-as-event-emitter.js:178:14)
at Object.onceWrapper (node:events:628:26)
at ClientRequest.emit (node:events:525:35)
at origin.emit (/var/tmp/pamac-build-shmuel/kuro/src/kuro-8.1.6/node_modules/@szmarczak/http-timer/source/index.js:37:11)
at TLSSocket.socketErrorListener (node:_http_client:490:9)
at TLSSocket.emit (node:events:513:28)
at emitErrorNT (node:internal/streams/destroy:151:8)
at emitErrorCloseNT (node:internal/streams/destroy:116:3)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
==> ERROR: A failure occurred in build().
Aborting…`

**Comment by Reverier-Xu** [comment]
> Thanks for publishing packages on AUR. You even have an App-image over there, which is great, because it installs on my Manjaro system without hitch. Could you maybe update the App-image on AUR to the newest version?

I apologize for the late reply, I'm infected with the covid-19 these days. I will update the newest version to AUR now. I don't have much time to spend on maintaining the package, so I can transfer the maintenance of this package to someone if it want to take over the maintenance.

**Comment by davidsmorais** [comment]
Thanks @Reverier-Xu :pray: I've also been busy with life affairs, will try to figure out how to work with AUR  in my Debian based OS and possibly add a manual deployment script so I can update the AUR package whenever I release a new version here/Snap.

**Comment by zjuyk** [comment]
Hi, tugyan had uploaded an AUR package [kuro](https://aur.archlinux.org/packages/kuro) which build from source.

BTW, please refer [nvcheck](https://github.com/lilydjwg/nvchecker) and [aurpublish](https://github.com/eli-schwartz/aurpublish) if you want to update AUR package per release.
