### ISSUE TITLE
[Bug 🐞]: Unexpected end of JSON input on startup

### ISSUE THREAD

**Issue by leonbohn** [davidsmorais/kuro#33]
# Unexpected end of JSON input on startup 🐞

**Describe the bug**
When attempting to launch the app, I get a JavaScript error and the process terminates.

**Reproduction Steps**
Just starting the app is enough to cause the crash, there is nothing I can do to prevent it.

**Expected Behavior**
I would like it if the app started as it did just a few days ago and I suspect starting up correctly would be the desired behaviour :grinning: 

**Technical Info (please complete the following information)**
 - OS: Arch Linux (full update just a few moments ago)
 - Kuro Version: 8.1.0

**Additional context**
I have tried to reinstall kuro and to delete the configuration files under ~/.config, both did nothing to help the problem. Whether I start from Gnome or directly through the terminal does not matter, the following error message is displayed:

> SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Config.get _local [as _local] (/opt/Kuro/resources/app.asar/src/config.js:15:19)
    at Config._ensureLocalConfig (/opt/Kuro/resources/app.asar/src/config.js:47:64)
    at Config.get configuration [as configuration] (/opt/Kuro/resources/app.asar/src/config.js:22:10)
    at Config.get shortcutKeys [as shortcutKeys] (/opt/Kuro/resources/app.asar/src/config.js:27:17)
    at Object.<anonymous> (/opt/Kuro/resources/app.asar/src/keymap.js:3:9)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Config._updateConfig (/opt/Kuro/resources/app.asar/src/config.js:33:12)
    at Config._ensureLocalConfig (/opt/Kuro/resources/app.asar/src/config.js:47:45)
    at Config.get configuration [as configuration] (/opt/Kuro/resources/app.asar/src/config.js:22:10)
    at Config.get shortcutKeys [as shortcutKeys] (/opt/Kuro/resources/app.asar/src/config.js:27:17)
    at Object.<anonymous> (/opt/Kuro/resources/app.asar/src/keymap.js:3:9)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment]
Hello @leonbohn , do you have any custom shortcuts enabled ?

**Comment by davidsmorais** [comment]
Hey  @alvarovm , 8.1.1 broke a few things 😅 My bad for not clearing my data while testing.

Please go ahead and try with [version 8.1.3 ](https://github.com/davidsmorais/kuro/releases/tag/v8.1.3)
